/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pedido;

/**
 *
 * @author Gehlen
 */
public class NovoPedidoForm extends javax.swing.JFrame {

    /**
     * Creates new form NovoPedidoForm
     */
    public NovoPedidoForm() {
        initComponents();
        lbErro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();
        btAlt = new javax.swing.JButton();
        btRm = new javax.swing.JButton();
        btCan = new javax.swing.JButton();
        lbPreco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btCon = new javax.swing.JButton();
        lbErro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 360));
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 320));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SABOR 1", "SABOR 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 452, 290);

        btAdd.setText("ADICIONAR");
        jPanel1.add(btAdd);
        btAdd.setBounds(470, 10, 320, 23);

        btAlt.setText("ALTERAR");
        jPanel1.add(btAlt);
        btAlt.setBounds(470, 50, 320, 23);

        btRm.setText("REMOVER");
        jPanel1.add(btRm);
        btRm.setBounds(470, 90, 320, 23);

        btCan.setText("CANCELAR");
        jPanel1.add(btCan);
        btCan.setBounds(470, 130, 320, 23);

        lbPreco.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbPreco.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel1.add(lbPreco);
        lbPreco.setBounds(520, 250, 270, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("R$");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 240, 60, 60);

        btCon.setText("CONCLUIR");
        jPanel1.add(btCon);
        btCon.setBounds(470, 210, 320, 23);

        lbErro.setForeground(new java.awt.Color(255, 51, 0));
        lbErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbErro.setText("SELECIONE AO MENOS UMA PIZZA");
        jPanel1.add(lbErro);
        lbErro.setBounds(10, 300, 450, 14);

        jButton1.setText("LISTAR");
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 170, 320, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAlt;
    private javax.swing.JButton btCan;
    private javax.swing.JButton btCon;
    private javax.swing.JButton btRm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbErro;
    private javax.swing.JLabel lbPreco;
    // End of variables declaration//GEN-END:variables
}
