/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;

/**
 *
 * @author Gehlen
 */
public class PizzaForm extends javax.swing.JFrame {

    /**
     * Creates new form PizzaForm
     */
    public PizzaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));
        jPanel1.setLayout(null);

        jRadioButton1.setText("CIRCULO");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(10, 30, 71, 23);

        jRadioButton2.setText("QUADRADO");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(10, 60, 93, 23);

        jRadioButton3.setText("TRIANGULO");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(10, 90, 83, 23);

        jLabel1.setText("Forma:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 34, 14);

        jLabel2.setText("Entre com a área:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 70, 320, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(170, 90, 320, 20);

        jCheckBox1.setText("Sabor 2");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(10, 220, 63, 23);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(10, 170, 480, 20);

        jLabel3.setText("Sabor 1");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 150, 480, 14);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(10, 250, 480, 20);

        jButton1.setText("ADICIONAR");
        jPanel1.add(jButton1);
        jButton1.setBounds(253, 310, 230, 23);

        jButton2.setText("CANCELAR");
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 310, 230, 23);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Valor inválido");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 110, 320, 14);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Valor inválido");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 50, 320, 14);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Valor inválido");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 270, 320, 14);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(170, 30, 320, 20);

        jLabel7.setText("Entre com o raio:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 10, 310, 14);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Valor inválido");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 190, 480, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
