/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;

/**
 *
 * @author Gehlen
 */
public class TipoForm extends javax.swing.JPanel {

    /**
     * Creates new form tipoPizzaForm
     */
    public TipoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfSimples = new javax.swing.JTextField();
        tfEspecial = new javax.swing.JTextField();
        tfPremium = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 330));

        jPanel1.setLayout(null);
        jPanel1.add(tfSimples);
        tfSimples.setBounds(20, 180, 460, 20);
        jPanel1.add(tfEspecial);
        tfEspecial.setBounds(20, 80, 460, 20);
        jPanel1.add(tfPremium);
        tfPremium.setBounds(20, 130, 460, 20);

        jButton1.setText("ATUALIZAR VALORES");
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 233, 460, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TABELA DE PREÇOS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 460, 40);

        jLabel2.setText("Premium:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 160, 460, 14);

        jLabel3.setText("Simples:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 460, 14);

        jLabel4.setText("Especial:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 460, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfEspecial;
    private javax.swing.JTextField tfPremium;
    private javax.swing.JTextField tfSimples;
    // End of variables declaration//GEN-END:variables
}
